#!/usr/bin/env node

/**
 * Auto-generate OpenClaw skills in catalog.json from extracted SKILL.md data.
 * Called by GitHub Action after building the Docker image.
 *
 * Usage: node scripts/update-catalog.js <version> <skills-tsv-file>
 *
 * The TSV file has lines: slug\tdescription\tenv_var
 * Generated by: docker run --rm <image> sh -c 'for dir in ...; do ... done'
 */

const fs = require('fs');

const version = process.argv[2];
const skillsFile = process.argv[3];

if (!version || !skillsFile) {
  console.error('Usage: node update-catalog.js <version> <skills.tsv>');
  process.exit(1);
}

const cat = JSON.parse(fs.readFileSync('catalog.json', 'utf8'));
const oc = cat.agents.find(a => a.name === 'openclaw');
if (!oc) {
  console.error('openclaw not found in catalog.json');
  process.exit(1);
}

// Update version + image
oc.version = version;
oc.image = `ghcr.io/lucid-fdn/lucid-agents/openclaw:v${version}`;

// Bundled skills (always auto-installed)
const BUNDLED = new Set([
  'weather', 'summarize', 'healthcheck', 'session-logs',
  'model-usage', 'clawhub', 'skill-creator',
]);

// Parse extracted skills from TSV
const raw = fs.readFileSync(skillsFile, 'utf8').trim().split('\n');
oc.skills = raw.map(line => {
  const [slug, desc, env] = line.split('\t');
  if (!slug) return null;

  const entry = {
    slug: slug.trim(),
    name: slug.trim()
      .replace(/-/g, ' ')
      .replace(/\b\w/g, c => c.toUpperCase()),
    description: (desc || '').trim().replace(/"/g, '').substring(0, 120),
  };

  if (BUNDLED.has(slug.trim())) entry.bundled = true;
  if (env && env.trim()) entry.env = env.trim();

  return entry;
}).filter(Boolean);

cat.generated_at = new Date().toISOString();
fs.writeFileSync('catalog.json', JSON.stringify(cat, null, 2) + '\n');

console.log(`Catalog updated: ${oc.skills.length} skills (${oc.skills.filter(s => s.bundled).length} bundled, ${oc.skills.filter(s => s.env).length} need keys)`);
